/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class speededUpRobustFeatures_TopSurfAlgorithm */

#ifndef _Included_speededUpRobustFeatures_TopSurfAlgorithm
#define _Included_speededUpRobustFeatures_TopSurfAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    load
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_load
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    computeSurf
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_computeSurf
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    extractSurfDescriptor
 * Signature: ([BIILspeededUpRobustFeatures/TopSurfVisualword;LspeededUpRobustFeatures/TopSurfDescriptor;)LspeededUpRobustFeatures/TopSurfDescriptor;
 */
JNIEXPORT jobject JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_extractSurfDescriptor
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobject, jobject);

/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    extractSurfDescriptorFile
 * Signature: (Ljava/lang/String;LspeededUpRobustFeatures/TopSurfVisualword;LspeededUpRobustFeatures/TopSurfDescriptor;)LspeededUpRobustFeatures/TopSurfDescriptor;
 */
JNIEXPORT jobject JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_extractSurfDescriptorFile
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    visualizeDescriptor
 */
JNIEXPORT jbyteArray JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_visualizeDescriptor
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);

/*
 * Class:     speededUpRobustFeatures_TopSurfAlgorithm
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_speededUpRobustFeatures_TopSurfAlgorithm_unload
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
